### ISSUE TITLE
Figure out how to aggregate data for time series graph

### ISSUE THREAD

**Issue by AyushChoudhury** [stoddabr/tahmo_rainQA#6]
Not implementation, just some initial exploration.

**Comment by michaelslater** [comment]
Assigned to Qiu

**Comment by stoddabr** [comment]
Javascript's map and reduce might be helpful here https://www.freecodecamp.org/news/javascript-map-reduce-and-filter-explained-with-examples/

**Comment by michaelslater** [comment]
We decided to go with static data and this data has been aggregated as of 11/28. We still need to figure out how to display this data in the web app, but this is a different issue.
