### ISSUE TITLE
Figure out how to use enviroment variables to hide API secrets

### ISSUE THREAD

**Issue by AyushChoudhury** [stoddabr/tahmo_rainQA#7]
Find a way to call the API without revealing API secrets. Write up instructions for how we use environment variables in Javascript.

**Comment by AyushChoudhury** [comment]
Assigned to Brett

**Comment by stoddabr** [comment]
Using environmental variables https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env
