### ISSUE TITLE
Lightning data

### ISSUE THREAD

**Issue by michaelslater** [stoddabr/tahmo_rainQA#9]
Write code that pulls down lightning data for a set of stations and converts it to a form the web implementation can use 

[assigned to Qiu + Michael]

**Comment by stoddabr** [comment]
How would the lightning information be integrated? Would it be on the map or in the weather graphs?

**Comment by michaelslater** [comment]
Sorry, didn't see the comment until now. The lightning would be an indicator either on the map or as an icon for each anomaly in the list. Lightning data was completed 11/28.
